# Generated by Django 6.0.1 on 2026-01-24 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcription_text', models.TextField(blank=True, help_text='Full transcript text')),
                ('transcription_confidence', models.FloatField(blank=True, help_text='Overall confidence score (0-1)', null=True)),
                ('transcription_language', models.CharField(default='en', help_text='Detected language code', max_length=10)),
                ('transcription_num_speakers', models.IntegerField(default=0, help_text='Number of speakers detected')),
                ('transcription_audio_duration', models.FloatField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('transcription_processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('transcription_segments', models.JSONField(blank=True, default=list, help_text='Array of segment objects with speaker, timing, text')),
                ('deepgram_response', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.TextField(blank=True, help_text='Human-readable summary')),
                ('summary_data', models.JSONField(blank=True, default=dict, help_text='Structured summary data')),
                ('summary_tokens', models.IntegerField(blank=True, help_text='Tokens used for summary', null=True)),
                ('summary_processing_time', models.FloatField(blank=True, help_text='Summary generation time in seconds', null=True)),
                ('summary_model_version', models.CharField(blank=True, max_length=50)),
                ('summary_response', models.JSONField(blank=True, default=dict, help_text='Raw Gemini response for summary')),
                ('action_items_text', models.TextField(blank=True, help_text='Human-readable action items')),
                ('action_items_data', models.JSONField(blank=True, default=dict, help_text='Structured action items')),
                ('action_items_tokens', models.IntegerField(blank=True, null=True)),
                ('action_items_processing_time', models.FloatField(blank=True, null=True)),
                ('action_items_model_version', models.CharField(blank=True, max_length=50)),
                ('action_items_response', models.JSONField(blank=True, default=dict)),
                ('key_points_text', models.TextField(blank=True, help_text='Human-readable key points')),
                ('key_points_data', models.JSONField(blank=True, default=dict, help_text='Structured key points')),
                ('key_points_tokens', models.IntegerField(blank=True, null=True)),
                ('key_points_processing_time', models.FloatField(blank=True, null=True)),
                ('key_points_model_version', models.CharField(blank=True, max_length=50)),
                ('key_points_response', models.JSONField(blank=True, default=dict)),
                ('sentiment_text', models.TextField(blank=True, help_text='Human-readable sentiment analysis')),
                ('sentiment_data', models.JSONField(blank=True, default=dict, help_text='Structured sentiment data')),
                ('sentiment_tokens', models.IntegerField(blank=True, null=True)),
                ('sentiment_processing_time', models.FloatField(blank=True, null=True)),
                ('sentiment_model_version', models.CharField(blank=True, max_length=50)),
                ('sentiment_response', models.JSONField(blank=True, default=dict)),
                ('total_tokens_used', models.IntegerField(default=0, help_text='Total tokens across all analyses')),
                ('total_processing_time', models.FloatField(default=0.0, help_text='Total processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recording',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow public access via share link'),
        ),
        migrations.AddField(
            model_name='recording',
            name='processing_progress',
            field=models.IntegerField(default=0, help_text='Processing progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='recording',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='public_share_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recordingfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['celery_task_id'], name='recordings__celery__5da465_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingfile',
            index=models.Index(fields=['user', '-created_at'], name='recordings__user_id_bec5bc_idx'),
        ),
        migrations.AddField(
            model_name='recordinganalysis',
            name='recording',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='recordings.recording'),
        ),
        migrations.AddField(
            model_name='recordinganalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recordinganalysis',
            index=models.Index(fields=['recording'], name='recordings__recordi_ab3714_idx'),
        ),
        migrations.AddIndex(
            model_name='recordinganalysis',
            index=models.Index(fields=['user', '-created_at'], name='recordings__user_id_d090ce_idx'),
        ),
    ]
