# Generated by Django 6.0.1 on 2026-01-24 13:11

from django.db import migrations


def migrate_processing_job_data(apps, schema_editor):
    """Migrate ProcessingJob data to Recording fields"""
    Recording = apps.get_model('recordings', 'Recording')
    
    # Skip if processing app doesn't exist (already migrated)
    try:
        ProcessingJob = apps.get_model('processing', 'ProcessingJob')
    except LookupError:
        print("\n=== ProcessingJob model not found (already migrated) ===")
        return
    
    print("\n=== Migrating ProcessingJob data to Recording ===")
    
    for job in ProcessingJob.objects.all():
        recording = job.recording
        recording.celery_task_id = job.celery_task_id
        recording.processing_progress = job.progress_percentage
        recording.processing_started_at = job.started_at
        recording.save(update_fields=['celery_task_id', 'processing_progress', 'processing_started_at'])
        print(f"  ✓ Migrated ProcessingJob for Recording {recording.id}")
    
    print(f"  Total: Migrated {ProcessingJob.objects.count()} ProcessingJobs")


def migrate_recording_file_users(apps, schema_editor):
    """Set user FK on RecordingFile from recording.user"""
    RecordingFile = apps.get_model('recordings', 'RecordingFile')
    
    print("\n=== Setting user FK on RecordingFile ===")
    
    for file in RecordingFile.objects.all():
        file.user = file.recording.user
        file.save(update_fields=['user'])
        print(f"  ✓ Set user for RecordingFile {file.id} ({file.file_type})")
    
    print(f"  Total: Updated {RecordingFile.objects.count()} RecordingFiles")


def migrate_transcription_data(apps, schema_editor):
    """Migrate Transcription and TranscriptionSegment to RecordingAnalysis"""
    Recording = apps.get_model('recordings', 'Recording')
    RecordingAnalysis = apps.get_model('recordings', 'RecordingAnalysis')
    
    # Skip if analysis app doesn't exist (already migrated)
    try:
        Transcription = apps.get_model('analysis', 'Transcription')
        TranscriptionSegment = apps.get_model('analysis', 'TranscriptionSegment')
    except LookupError:
        print("\n=== Transcription models not found (already migrated) ===")
        return
    
    print("\n=== Migrating Transcription data to RecordingAnalysis ===")
    
    for transcription in Transcription.objects.all():
        recording = transcription.recording
        
        # Get or create RecordingAnalysis
        analysis, created = RecordingAnalysis.objects.get_or_create(
            recording=recording,
            defaults={'user': recording.user}
        )
        
        if not created and analysis.user is None:
            analysis.user = recording.user
        
        # Migrate transcription fields
        analysis.transcription_text = transcription.full_text
        analysis.transcription_confidence = transcription.confidence_score
        analysis.transcription_language = transcription.language_detected
        analysis.transcription_num_speakers = transcription.num_speakers
        analysis.transcription_audio_duration = transcription.audio_duration_seconds
        analysis.transcription_processing_time = transcription.processing_time_seconds
        analysis.deepgram_response = transcription.deepgram_response
        
        # Migrate transcription segments to JSON array
        segments = []
        for segment in TranscriptionSegment.objects.filter(transcription=transcription).order_by('start_time_seconds'):
            segments.append({
                'start': segment.start_time_seconds,
                'end': segment.end_time_seconds,
                'text': segment.text,
                'confidence': segment.confidence_score,
                'speaker_id': segment.speaker_id,
                'speaker_label': segment.speaker_label,
                'words': segment.words,
            })
        
        analysis.transcription_segments = segments
        analysis.save()
        
        action = "Created" if created else "Updated"
        print(f"  ✓ {action} RecordingAnalysis for Recording {recording.id} (transcription with {len(segments)} segments)")
    
    print(f"  Total: Migrated {Transcription.objects.count()} Transcriptions")


def migrate_ai_analysis_data(apps, schema_editor):
    """Migrate AIAnalysis records to RecordingAnalysis fields"""
    RecordingAnalysis = apps.get_model('recordings', 'RecordingAnalysis')
    
    # Skip if analysis app doesn't exist (already migrated)
    try:
        AIAnalysis = apps.get_model('analysis', 'AIAnalysis')
    except LookupError:
        print("\n=== AIAnalysis model not found (already migrated) ===")
        return
    
    print("\n=== Migrating AIAnalysis data to RecordingAnalysis ===")
    
    type_mapping = {
        'summary': 'summary',
        'action_items': 'action_items',
        'key_points': 'key_points',
        'sentiment': 'sentiment',
    }
    
    migrated_count = 0
    
    for ai_analysis in AIAnalysis.objects.all():
        recording = ai_analysis.recording
        analysis_type = ai_analysis.analysis_type
        
        # Get or create RecordingAnalysis
        analysis, created = RecordingAnalysis.objects.get_or_create(
            recording=recording,
            defaults={'user': recording.user}
        )
        
        if not created and analysis.user is None:
            analysis.user = recording.user
        
        # Map to appropriate field prefix
        field_prefix = type_mapping.get(analysis_type)
        if not field_prefix:
            print(f"  ⚠ Skipping unknown analysis type: {analysis_type}")
            continue
        
        # Set the fields dynamically
        setattr(analysis, f'{field_prefix}_text', ai_analysis.result_text)
        setattr(analysis, f'{field_prefix}_data', ai_analysis.result_data)
        setattr(analysis, f'{field_prefix}_tokens', ai_analysis.tokens_used)
        setattr(analysis, f'{field_prefix}_processing_time', ai_analysis.processing_time_seconds)
        setattr(analysis, f'{field_prefix}_model_version', ai_analysis.model_version)
        setattr(analysis, f'{field_prefix}_response', ai_analysis.gemini_response)
        
        analysis.save()
        migrated_count += 1
        
        print(f"  ✓ Migrated {analysis_type} for Recording {recording.id}")
    
    print(f"  Total: Migrated {migrated_count} AIAnalysis records")
    
    # Update totals for all RecordingAnalysis
    print("\n=== Calculating totals for RecordingAnalysis ===")
    for analysis in RecordingAnalysis.objects.all():
        analysis.total_tokens_used = sum(filter(None, [
            analysis.summary_tokens,
            analysis.action_items_tokens,
            analysis.key_points_tokens,
            analysis.sentiment_tokens,
        ]))
        analysis.total_processing_time = sum(filter(None, [
            analysis.transcription_processing_time or 0,
            analysis.summary_processing_time or 0,
            analysis.action_items_processing_time or 0,
            analysis.key_points_processing_time or 0,
            analysis.sentiment_processing_time or 0,
        ]))
        analysis.save(update_fields=['total_tokens_used', 'total_processing_time'])
        print(f"  ✓ Updated totals for Recording {analysis.recording.id}: {analysis.total_tokens_used} tokens, {analysis.total_processing_time:.2f}s")


def reverse_migration(apps, schema_editor):
    """Reverse migration - delete RecordingAnalysis data and clear Recording fields"""
    Recording = apps.get_model('recordings', 'Recording')
    RecordingAnalysis = apps.get_model('recordings', 'RecordingAnalysis')
    RecordingFile = apps.get_model('recordings', 'RecordingFile')
    
    print("\n=== Reversing data migration ===")
    
    # Delete all RecordingAnalysis
    count = RecordingAnalysis.objects.count()
    RecordingAnalysis.objects.all().delete()
    print(f"  ✓ Deleted {count} RecordingAnalysis records")
    
    # Clear Recording fields
    Recording.objects.update(
        celery_task_id='',
        processing_progress=0,
        processing_started_at=None
    )
    print(f"  ✓ Cleared ProcessingJob fields from {Recording.objects.count()} Recordings")
    
    # Clear RecordingFile user FK
    RecordingFile.objects.update(user=None)
    print(f"  ✓ Cleared user FK from {RecordingFile.objects.count()} RecordingFiles")


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_add_consolidated_models'),
        # Note: Dependencies on 'processing' and 'analysis' removed after cleanup
    ]

    operations = [
        migrations.RunPython(migrate_processing_job_data, reverse_migration),
        migrations.RunPython(migrate_recording_file_users, migrations.RunPython.noop),
        migrations.RunPython(migrate_transcription_data, migrations.RunPython.noop),
        migrations.RunPython(migrate_ai_analysis_data, migrations.RunPython.noop),
    ]
